name: CI - QueueLens

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Upload QueueLens frontend build (dist)
        uses: actions/upload-artifact@v4
        with:
          name: queuelens-frontend-dist
          path: |
            dist

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install frontend dependencies
        run: npm ci

      - name: Run frontend lint/tests (if present)
        run: |
          set -e
          npm run lint --if-present
          npm test --if-present -- --ci
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest
        shell: bash

      - name: Backend quick check + tests (if any)
        run: |
          set -e
          python -m py_compile main.py

          if [ -d tests ] || ls -1 test_*.py 2>/dev/null | grep -q .; then
            pytest -q | tee test_results.txt
          else
            echo "No backend tests found; skipping pytest." | tee test_results.txt
          fi
        shell: bash

      - name: Upload test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: queuelens-test-results
          path: |
            test_results.txt
